# Generated by Django 4.1.4 on 2022-12-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0003_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='live',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
