# Generated by Django 4.1.4 on 2022-12-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0004_project_github_project_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='live',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
